### ISSUE TITLE
wangchen的art介绍视频中的ppt能否发一下链接，没有找到

### ISSUE THREAD

**Issue by dddjpy** [isrc-cas/PLCT-Open-Reports#56]
https://www.bilibili.com/video/BV1wC4y1t7Xa
就是这一节的ppt。找了几遍没有找到，可否把链接直接发出来，感谢！

**Comment by lazyparser** [comment]
收到，我来联系下作者发PR提交上来

**Comment by lazyparser** [comment]
https://github.com/isrc-cas/PLCT-Open-Reports/pull/57

已经上传
